#!/bin/sh
BRANCH=`git status | grep "On branch" | awk '{print $4}'`
git diff gitmake > patches-tmp/${BRANCH}_`cat gitmake-origin`.diff
ln -sf ../${BRANCH}_`cat gitmake-origin`.diff patches-tmp/current/${BRANCH}.diff
